### PR TITLE
export emscripten filesystem

### PR DESCRIPTION
**Pull request by dfinityio**

### CODE REVIEW

**Comment by feelfreelinux** [comment]
Looks good, thanks!

**Comment by dfinityio** [comment]
I should create PR in the master branch. 😱

**Comment by feelfreelinux** [comment]
@dfinityio merged it
https://github.com/feelfreelinux/td/pull/2/

**Comment by dfinityio** [comment]
thanks!

**Comment by dfinityio** [comment]
@feelfreelinux Sorry! I review at ```td_wasm.js``` and found out that FS had exported filesystems, they existed in ```FS.filesystems```. It seems that I made a useless PR. Please reset commit.

**Pull request merged**
